/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Action } from "./Action";
import { ActionCountArgs } from "./ActionCountArgs";
import { ActionFindManyArgs } from "./ActionFindManyArgs";
import { ActionFindUniqueArgs } from "./ActionFindUniqueArgs";
import { DeleteActionArgs } from "./DeleteActionArgs";
import { ActionService } from "../action.service";
@graphql.Resolver(() => Action)
export class ActionResolverBase {
  constructor(protected readonly service: ActionService) {}

  async _actionsMeta(
    @graphql.Args() args: ActionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Action])
  async actions(@graphql.Args() args: ActionFindManyArgs): Promise<Action[]> {
    return this.service.actions(args);
  }

  @graphql.Query(() => Action, { nullable: true })
  async action(
    @graphql.Args() args: ActionFindUniqueArgs
  ): Promise<Action | null> {
    const result = await this.service.action(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Action)
  async deleteAction(
    @graphql.Args() args: DeleteActionArgs
  ): Promise<Action | null> {
    try {
      return await this.service.deleteAction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
